# Generated by Django 5.0 on 2023-12-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="default/default-user.png",
                upload_to="images/profile_pics",
            ),
        ),
    ]
